---
name: adrianvilllanueva
services:
  adrianvillanueva:
    image: ghcr.io/adrianvillanueva997/adrianvillanueva.com:v2.1.0@sha256:63c3245a828be7154a0ff71365c40fdf639e59ad37250b82763bd3a4bb70901b
    networks:
      - proxy
    container_name: adrianvillanueva.com
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.adrianvillanueva-redirect-https.redirectscheme.scheme=https
      - traefik.http.middlewares.adrianvillanueva-redirect-https.redirectscheme.permanent=true
      - traefik.http.routers.adrianvillanueva-http.middlewares=adrianvillanueva-redirect-https
      - traefik.http.routers.adrianvillanueva-http.rule=Host(`adrianvillanueva.com`)
      - traefik.http.routers.adrianvillanueva-http.entrypoints=http
      - traefik.http.routers.adrianvillanueva-https.rule=Host(`adrianvillanueva.com`)
      - traefik.http.routers.adrianvillanueva-https.tls.certresolver=le
      - traefik.http.routers.adrianvillanueva-https.tls=true
      - traefik.http.routers.adrianvillanueva-https.entrypoints=https
      - traefik.docker.network=proxy
    # env_file:
      # - stack.env
networks:
  proxy:
    external: true
