version: "3.0"
services:
  api:
    image: adrianvillanueva997/adrian-villanueva.com
    networks:
      - proxy
    container_name: adrian-villanueva.com
    restart: unless-stopped
    labels:
      - - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.avm-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.avm-redirect-websecure.redirectscheme.permanent=true"
      - "traefik.http.routers.avm-web.middlewares=avm-redirect-websecure"
      - traefik.http.routers.avm-web.rule=Host(`adrian-villanueva.com`)
      - traefik.http.routers.avm-web.entrypoints=web
      - traefik.http.routers.avm-websecure.rule=Host(`adrian-villanueva.com`)
      - traefik.http.routers.avm-websecure.tls.certresolver=le
      - traefik.http.routers.avm-websecure.tls=true
      - traefik.http.routers.avm-websecure.entrypoints=web-secured
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true