version: "3.0"
services:
  web:
    image: ghcr.io/adrianvillanueva997/blog-adrian-villanueva:latest@sha256:ece0c7182e55ba93624bd221a71c8bc8bbe58db3488a1145c4d9201fe53ddac4
    networks:
      - proxy
    container_name: blog-adrian-villanueva.com
    restart: unless-stopped
    labels:
      - com.ouroboros.enable=true
      - "traefik.enable=true"
      - "traefik.http.middlewares.avm-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.avm-redirect-websecure.redirectscheme.permanent=true"
      - "traefik.http.routers.avm-web.middlewares=avm-redirect-websecure"
      - traefik.http.routers.avm-web.rule=Host(`adrianvillanueva.com`)
      - traefik.http.routers.avm-web.entrypoints=http
      - traefik.http.routers.avm-websecure.rule=Host(`adrianvillanueva.com`)
      - traefik.http.routers.avm-websecure.tls.certresolver=le
      - traefik.http.routers.avm-websecure.tls=true
      - traefik.http.routers.avm-websecure.entrypoints=https
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
