apiVersion: apps/v1
kind: Deployment
metadata:
  name: adrianvillanueva
  namespace: adrianvillanueva
spec:
  selector:
    matchLabels:
      app: adrianvillanueva
  replicas: 1
  template:
    metadata:
      labels:
        app: adrianvillanueva
    spec:
      containers:
        - name: adrianvillanueva
          image: ghcr.io/adrianvillanueva997/adrianvillanueva.com:v2.1.0@sha256:63c3245a828be7154a0ff71365c40fdf639e59ad37250b82763bd3a4bb70901b
          ports:
            - containerPort: 8080

      restartPolicy: Always
