apiVersion: apps/v1
kind: Deployment
metadata:
  name: adrianvillanueva
  namespace: adrianvillanueva
spec:
  selector:
    matchLabels:
      app: adrianvillanueva
  replicas: 1
  template:
    metadata:
      labels:
        app: adrianvillanueva
    spec:
      containers:
        - name: adrianvillanueva
          image: ghcr.io/adrianvillanueva997/adrianvillanueva.com:v2.1.1@sha256:3215364f8b76a3b7119be291efa1990254ab208c40b13d6fe8a03986d37913d7
          ports:
            - containerPort: 8080

      restartPolicy: Always
