name: Development building
on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up CD
        uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Set up Docker Qemu
        uses: docker/setup-qemu-action@v3.0.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/adrianvillanueva997/adrian-villanueva:dev
          labels: ${{ steps.meta.outputs.labels }}
