name: Development building
on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  security-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Override automatic language detection by changing the below list
        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']
        language: [ 'javascript' ]
        # Learn more...
    container:
      image: node:16.13.0-alpine
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install & Tests
        run: |
          npm install
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  install-deps:
    runs-on: ubuntu-latest
    container: node:16.13.0-alpine
    steps:
      - uses: actions/checkout@v2.3.4
      - name: build & install dependencies
        run: |
          npm i && npm run build
  build-docker:
    runs-on: ubuntu-latest
    needs:
      - security-check
      - install-deps
    steps:
      - name: Set up CD
        uses: actions/checkout@v2.4.0
      - name: Set up Docker Qemu
        uses: docker/setup-qemu-action@v1.2.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Docker login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@548e2346a9987b56d8a4104fe776321ff8e23440
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/adrianvillanueva997/adrian-villanueva:dev
          labels: ${{ steps.meta.outputs.labels }}



