name: Build Docker image

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up CD
        uses: actions/checkout@v2.4.0
      - name: Set up Docker Qemu
        uses: docker/setup-qemu-action@v1.2.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
