name: Build Docker image

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up CD
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Docker Qemu
        uses: docker/setup-qemu-action@v3.0.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
